### ISSUE TITLE
Looks like Wine 8.18 mediacontrol changes broke Roon

### ISSUE THREAD

**Issue by roband7** [RoPieee/roon-on-wine#39] opened 2023-10-16 19:38 UTC
Crashes as soon as an audio zone is selected.

011c:err:eventlog:ReportEventW L"Application: Roon.exe\n"
011c:err:eventlog:ReportEventW L"CoreCLR Version: 6.0.2123.36311\n"
011c:err:eventlog:ReportEventW L".NET Version: 6.0.21\n"
011c:err:eventlog:ReportEventW L"Description: The process was terminated due to an internal error in the .NET Runtime at IP 00006FFFFDE32699 (00006FFFFDC60000) with exit code c0000005.\n"

**Comment by Younday** [comment] 2023-10-17 08:14
I've gotten a crash on startup after installing Wine 8.18. I've tried reverting to 8.17, but no luck so far.

**Comment by Younday** [comment] 2023-10-17 08:35
I've had a working version until version 8.17 of Wine on Kubuntu 23.04. After upgrading to 8.18, I received the error I posted in my previous message, so I assumed something broke in version 8.18 specifically. Reverting actually seems to be working fine, but it required reinstalling Roon using the `install.sh` script. 

The following command should work in (K)ubuntu to install version 8.17:

```
sudo apt install winehq-staging=8.17~lunar-1 wine-staging=8.17~lunar-1 wine-staging-amd64=8.17~lunar-1 wine-staging-i386=8.17~lunar-1
```

Afterward, I deleted my `start_my_roon_instance.sh` file and reran `install.sh` and Roon seems to be working fine again. In case you want to avoid accidentally upgrading to version 8.18 again during `apt upgrade`, you can use the following command to pin it to the current version:

```
sudo apt-mark hold winehq-staging wine-staging wine-staging-amd64 wine-staging-i386
```

**Comment by roband7** [comment] 2023-10-17 08:39
Thanks, that confirms my suspicion the 8.18 changes break Roon.

So we need to stay at 8.17 or earlier for now.

Unless someone can figure out a workaround and update the roon-on-wine script.

**Comment by fiddlesticks** [comment] 2023-10-29 16:22
Thanks! The command you suggested (with a small variant, see below) fixed it for me on Linux Mint 21.2

sudo apt install winehq-staging=8.17~jammy-1 wine-staging=8.17~jammy-1 wine-staging-amd64=8.17~jammy-1 wine-staging-i386=8.17~jammy-1

**Comment by chetwisniewski** [comment] 2023-10-30 00:05
I installed 8.19 which was released this morning and it fixes it after a re-run of the ropieeee-rooninstall.sh script. I have compiled 8.19 for Arch until the official maintainer updates the main package, if you trust me you can obtain it here: https://cloud.zuzax.com/s/5666ZtkgqyK7wdX

**Comment by chetwisniewski** [comment] 2023-10-30 00:08
I downloaded and compiled 8.19 which was released this morning for Arch Linux. It fixes the initial error in the .NET runtime, but if you select a Zone that is playing music it now throws another error: 

`wine: Call from 00006FFFFFC53C07 to unimplemented function shcore.dll.CreateRandomAccessStreamOverStream, aborting
`

**Comment by ThatDonna** [comment] 2023-11-03 04:25
Wine staging 8.19 was just released. Tested it here and it looks like Roon works fine again. 

Running Linux Mint 21.2

**Comment by Bananas-Are-Yellow** [comment] 2023-11-03 08:46
> Wine staging 8.19 was just released. Tested it here and it looks like Roon works fine again.
> 
> Running Linux Mint 21.2
```
$ wine --version
wine-8.19 (Staging)
```
It is not working for me on Pop!_OS 22.04 LTS. If no audio zone has been selected it comes up, but as soon as you select an audio zone it crashes. Then it crashes each time you start it.

**Comment by orsib78** [comment] 2023-11-03 12:31
Wine staging 8.19 doesn't work on Ubuntu 23.10 either. Even when I tried to reinstall ROW from scratch.

**Comment by ThatDonna** [comment] 2023-11-04 00:15
@Bananas-Are-Yellow, @orsib78 
I confirmed a similar issue on my instance.

What I observe:
* Reinstall the instance (via install.sh)
* Connect to Core
* The first run, no Audio Zone is selected. I am able to select an initial Audio Zone with no issue.
* If I choose to select a different Audio Zone from the first one, or play a song, I get the following error:

`wine: Call from 00006FFFFF443A67 to unimplemented function shcore.dll.CreateRandomAccessStreamOverStream, aborting`

* At that point, Roon crashes. And, similarly, it crashes each time I start it with the above error.

Sigh. Spoke too soon.

**Comment by Bananas-Are-Yellow** [comment] 2023-11-14 08:05
It works!
Well done @IcedEagle.
And many thanks.

**Comment by ThatDonna** [comment] 2023-11-17 15:39
Wine 8.20 was released and I tested it on my Linux Mint instance -- same error as above:

- Reinstall the instance (via install.sh)
- Connect to Core
- The first run, no Audio Zone is selected. I am able to select an initial Audio Zone with no issue.
- I'm able to select between different Audio Zones
- When I play a song:
`wine: Call from 00006FFFFF443A67 to unimplemented function shcore.dll.CreateRandomAccessStreamOverStream, aborting
`
- At that point, Roon crashes. And, similarly, it crashes each time I start it with the above error.

I'm staying with @fiddlesticks' reversion to wine 8.17.

**Comment by spockfish** [comment] 2023-11-21 08:51
I've added the change proposed by @IcedEagle , so let's close this ticket for now.

Thanks @IcedEagle !

**Closed by spockfish** 2023-11-21 08:51 UTC

**Comment by ThatDonna** [comment] 2023-12-15 17:57
Hi all --

I just checked the script with the new wine-9.0-rc1, per @IcedEagle's submitted wine bug (https://bugs.winehq.org/show_bug.cgi?id=55867).

I get a slightly different error now.

* Reinstall the instance (via install.sh without the work around)
* Connect to Core
* On the first run, no Audio Zone is selected
* I select an Audio Zone and get the following error, then Roon crashes
`0114:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Storage.Streams.RandomAccessStreamReference"`
* Roon crashes when I restart it with the same error

**Comment by ThatDonna** [comment] 2023-12-27 23:06
@IcedEagle Added! I just re-checked given RC3, same issue.

https://bugs.winehq.org/show_bug.cgi?id=56106
